# -*- encoding: utf-8 -*-

require File.expand_path('../lib/generator/version.rb', __FILE__)

Gem::Specification.new do |s|
  s.name = "ffi-swig-generator"
  s.version = FFI::Generator::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrea Fazzi"]
  s.date = "2013-10-19"
  s.description = "ffi-swig-generator is a ruby-ffi wrapper code generator that produces\nruby-ffi glue code parsing C header files through SWIG.\n\nffi-swig-generator is able to traverse an XML parse tree generated by\nthe +swig+ command and to produce a ruby-ffi code from it.\n\nffi-swig-generator is shipped with a command line tool and a rake task\nthat automates the code generation process.\n\nffi-swig-generator XML capabilities are provided by nokogiri."
  s.email = "andrea.fazzi@alcacoop.it"
  s.executables = ["ffi-gen"]
  s.extra_rdoc_files = ["History.txt", "README.rdoc", "bin/ffi-gen"]
  s.files = %x{git ls-files}.split("\n")
  s.homepage = "http://github.com/ffi/ffi-swig-generator"
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "ffi-swig-gen"
  s.rubygems_version = "1.8.24"
  s.summary = "ffi-swig-generator is a ruby-ffi wrapper code generator that produces ruby-ffi glue code parsing C header files through SWIG"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.9.2.2"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6.0"])
      s.add_runtime_dependency('ffi')
    else
      s.add_dependency(%q<rake>, [">= 0.9.2.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.6.0"])
      s.add_dependency('ffi')
    end
  else
    s.add_dependency(%q<rake>, [">= 0.9.2.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.6.0"])
    s.add_dependency('ffi')
  end
end
