%module enum_test

enum e { PREFIX_FIRST, PREFIX_SECOND, PREFIX_THIRD };
enum e_2 { COMMON_FIRST = 2, COMMON_SECOND, COMMON_THIRD };
enum e_3 { AGAIN_FIRST, AGAIN_SECOND = 5, AGAIN_THIRD };
enum e_4 { E3_0, E3_1, E3_2 };
enum e_5 { ABSURD_ENUM_WITH_ONE_KEY };
