# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-swig-generator}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrea Fazzi"]
  s.date = %q{2009-03-06}
  s.default_executable = %q{ffi-gen}
  s.description = %q{ffi-swig-generator is a ruby-ffi wrapper code generator based on SWIG interface files.  ffi-swig-generator is able to traverse a XML parse tree file generated by the +swig+ command and to produce a ruby-ffi interface file from it.  ffi-swig-generator is shipped with a command line tool (ffi-gen) and a rake task that automates the code generation process.  ffi-swig-generator XML capabilities are provided by nokogiri.}
  s.email = %q{andrea.fazzi@alcacoop.it}
  s.executables = ["ffi-gen"]
  s.extra_rdoc_files = ["History.txt", "README.rdoc", "bin/ffi-gen"]
  s.files = [".gitignore", "History.txt", "README.rdoc", "Rakefile", "bin/ffi-gen", "examples/Rakefile", "examples/interfaces/libc.i", "examples/interfaces/wiiuse.i", "ffi-swig-generator.gemspec", "lib/ffi-swig-generator.rb", "lib/generator/application.rb", "lib/generator/generator.rb", "lib/generator/generatortask.rb", "spec/ffi-swig-generator_spec.rb", "spec/generator/generator_spec.rb", "spec/generator/swig/constants.i", "spec/generator/swig/enums.i", "spec/generator/swig/functions.i", "spec/generator/swig/structs.i", "spec/generator/swig/testlib.i", "spec/generator/swig/typedefs.i", "spec/generator/swig/types.i", "spec/generator/swig/unions.i", "spec/spec.opts", "spec/spec_helper.rb", "tasks/ann.rake", "tasks/bones.rake", "tasks/gem.rake", "tasks/git.rake", "tasks/notes.rake", "tasks/post_load.rake", "tasks/rdoc.rake", "tasks/rubyforge.rake", "tasks/setup.rb", "tasks/spec.rake", "tasks/svn.rake", "tasks/test.rake"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/remogatto/ffi-swig-generator/tree/master}
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ffi-swig-generator}
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{ffi-swig-generator is a ruby-ffi wrapper code generator based on SWIG interface files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.3"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.2.1"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.3"])
      s.add_dependency(%q<nokogiri>, [">= 1.2.1"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.3"])
    s.add_dependency(%q<nokogiri>, [">= 1.2.1"])
  end
end
