module FFI
  module Generator
    TYPES = {
      'bool' => ':bool',
      'char' => ':char',
      'double' => ':double',
      'float' => ':float',
      'unsigned long' => ':ulong',
      'unsigned char' => ':uchar',
      'signed char' => ':char',
      'unsigned char' => ':uchar',
      'short' => ':short',
      'signed short'     => ':short',
      'signed short int' => ':short',
      'unsigned short'     => ':ushort',
      'unsigned short int' => ':ushort',
      'int' => ':int',
      'int8_t' => ':int8',
      'int16_t' => ':int16',
      'int32_t' => ':int32',
      'int64_t' => ':int64',
      'intptr_t' => ':__intptr_t',
      'signed int' => ':int',
      'unsigned int' => ':uint',
      'uint8_t' => ':uint8',
      'uint16_t' => ':uint16',
      'uint32_t' => ':uint32',
      'uint64_t' => ':uint64',
      'long' => ':long',
      'long int' => ':long',
      'signed long' => ':long',
      'signed long int' => ':long',
      'unsigned long' => ':ulong',
      'unsigned long int' => ':ulong',
      'long unsigned int' => ':ulong',
      'long long'     => ':long_long',
      'long long int' => ':long_long',
      'signed long long'     => ':long_long',
      'signed long long int' => ':long_long',
      'size_t' => ':size_t',
      'unsigned long long'     => ':ulong_long',
      'unsigned long long int' => ':ulong_long',
      'void' => ':void'
    }
  end
end
